# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import sphinx_rtd_theme
sys.path.insert(0, os.path.abspath('../'))
sys.path.insert(0, os.path.abspath('../rutinas'))
sys.path.insert(0, os.path.abspath('../handlers'))
sys.path.insert(0, os.path.abspath('../promociones'))
sys.path.insert(0, os.path.abspath('../handlers'))

def skip(app, what, name, obj, skip, options):
    if name == "__init__":
        return False
    return skip

def setup(app):
    app.connect("autodoc-skip-member", skip)
    
# -- Project information -----------------------------------------------------

project = 'Laboratorio Virtual de sistemas de control clásicos y difusos utilizando software libre'
copyright = '2020, Kleiver J. Carrasco M.'
author = 'Kleiver J. Carrasco M.'

# The full version, including alpha/beta/rc tags
release = '1.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.coverage', 'sphinx.ext.viewcode']
#'sphinx.ext.napoleon , 'rst2pdf.pdfbuilder''
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
master_doc = 'index'
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'es'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
html_theme_path = sphinx_rtd_theme.get_html_theme_path()

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

latex_documents = [
    (master_doc, 'LaboratorioVirtual.tex', 'Laboratorio Virtual de sistemas de control clásicos y difusos utilizando software libre',
     'Kleiver J. Carrasco M.', 'manual'),
]

man_pages = [
    (master_doc, 'LaboratorioVirtual', 'Laboratorio Virtual de sistemas de control clásicos y difusos utilizando software libre',
     [author], 1)
]

texinfo_documents = [
    (master_doc, 'LaboratorioVirtual', 'Laboratorio Virtual de sistemas de control clásicos y difusos utilizando software libre',
     author, 'LaboratorioVirtual', 'One line description of project.',
     'Miscellaneous'),
]

autodoc_mock_imports = ["discreto_sim", "metodos_RK","rutinas.discreto_sim", "rutinas.metodos_RK"]